!group
id: authentication_group
name: Authentication
desc: |
    Holocentric BMS uses OAuth for the service authentication. This authentication mechanism requires an initial call to authenticate the API user based on the user name and password provided, and will then return an access token. This access token has a default expirt time of 8 hours. The API user must be a licensed user with the System Authority role 'API Client (Full Read)' assigned in order to be able to authenticate with the service. This user will have access to all mapped properties of the service.
    
    The token that is received can then be used for subsequent API requests. 
    
    > Please note the following:
    > - Tokens must not be shared; only the requesting IP address can use the token provided.
    > - Subsequent requests for a token within the 8 hour expiry period will not expire existing valid tokens.
